archive:
  path: /path/to/archive/
  
import:
  path: /path/to/import/
  
solr:
  index:
    url: http://solr.url
    
spring:
  resources:
    static-locations: classpath:/static/
  http:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
