spring:
  resources:
    static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: "1024MB"
      max-request-size: "1024MB"

archive:
  path: /path/to/archive/
  
import:
  path: /path/to/import/
  
solr:
  index:
    url: http://solr.url
    